
#include "Main.h"

#include "Asserts/ConfigReleaseChecked.h"
#include "Datatypes/Number.h"
#include "Utils/GenerationalPointer.cpp"
#include "Utils/IComparison.cpp"
#include "Polymorphic/IAny.cpp"
#include "Polymorphic/IMany.cpp"
#include "Interpreter/IMacroList.cpp"
#include "Datatypes/Tuple.cpp"
#include "Datatypes/Function.cpp"

//TODOs:
//Remove all IManys after prototyping
//Use generationalPointers for regular pointers
//Postconditions/preconditions for everything: test only function-related values, test all class invariants, don't test interfunctional relations with conditions
//Change all numeric integer types to number_ (all indices etc)
//  Find library that's "optimized for small case"
//Convert everything to free functions (Add UFCS later)
//Combine SequenceBuilder and FunctionBuilder; Separate out Function and Sequence execution
//A class to implement the static max_id; map<id, data>; value() = map[id] pattern (Use a single max_id for all classes)

//Design:
/*
*   Describe an imperative, low-level language over Tuples, with determinism, purity, and static_asserts
*       Includes Sequences, Functions, Sequence Executions
*       The "type" of a sequence is the full definition of it, the type of a pure function is the map of its inputs to outputs
*   Describe a "heritable meta-context" describing impure additions to the low-level language and hygienic macros
*   Describe a higher-level language, representing an "optimization contract" over the lower-level language
*       describes the allowed optimizations of the implemented code
*       include theories and static_asserts; describe the allowed/expected behaviours
*       use constants from the heritable meta-context to describe compiler passes to apply different compiler passes
*/

//Optimizations:

//"Free" optimizations: (Can be performed without non-trivial search optimizations)
//Propagate constants fully
//Replace all variables with (function+state) such that it evaluates equal to the variable at that value
//Monomorphize all function calls on the call-site  f(int a, int b) -> f(3, b) etc
//Monomorphize all theories (eg int a, b; -> int1 a; int2 b;)
//Strengthen all theories from the end  int c := a + b -> int(a + b) c := a + b
// Reduce function-types of outputs' codomain to match function-types of inputs' domain
//Delay all computation "production" until "consumption" in the sequence
//Weaken all theories to only match requirements for all "consumption"

//Purify pass:
//Strength reduction of bounded loops to for(i = 0; i != ...; i++) { /*No writes to i*/; }
//Eliminate all bounded recursion with monomorphization (ie f(3, a) = f(2, b) + c becomes f_3(a) = f_2(b) + c)
//  Transform to non-recursive functions with basecases
//Sequence-Invariant code motion: Useful for loops and branches
//  Moves code representing constraints "outside" sequences that retain those constraints
//Replace all variables with "const shadowing CoWs"
//  ie a = a+1
//   to
//  a2 = a1 + 1
//Merge all unbounded loops program-wide into a single unbounded loop with a single inductor+local variables
//  eg convert 
//      generate(x):
//          co_return next x;
//      generate(y):
//          co_return next y;
//      generate(z):
//          generate(x);
//          generate(y);
//          co_return next z;
//      to
//      generate(z):
//          next x;
//          next y;
//          co_return next z;

//Search pass: (Opposites)
//Monomorphize functions <-> deduplicate ("template-ize") functions
//Inline function calls <-> extract function calls
//Cache vs "functionize" pure variables
//eg
//  a = b + c
//  f(a)
// to/from
//  f(b + c)
//Complete "conditional" theories by solving for the unconditional result, to facilitate "Sequence-invariant code motion"

//Representation pass:
//Represent theories with restrictions on Tuples (ie f[input] = fixed)
//Solve for theory representations by solving (f[input] = fixed)
// Functions with multiple inputs (by tying multiple inputs together)
// Functions that are partially applied are functions with some inputs specified
// 
//Describe "infinities" with generators, switch between different stateless representations
//Purify all computation with "pure" and "impure" sections, separating their cones of influence
// 
// Equivalence class relations split the input into two factors; an equivalence member and an equivalence result
// The "equivalence result" is a single unique representation of the equivalence class
// Different members of the equivalence class can be represented with equivalence results, and can be compared (both == and !=) by comparing the equivalence result
// The equivalence result can be found by brute-forcing the solution to "equivalence_class[a] == equivalence_class[b]"
//
//eg can represent infinity with x such that x - 1 = x (the result of x - 1 has been generated by the definition)
//Representing a generator over a different domain needs (possibly hidden) statefulness, but without representation is stateless
//eg Infinity can also be represented like x such that n < x for all n in N.
//  This can be "approximated statefully" by using a number_ n', which is actually in N, but is bigger than all elements in the discourse.
//  These approximations have to be stateful because eg the "discourse" is stateful (eg as new inputs are received, the "largest" number_ has to be increased)
//  Generating a "stateful" approximation from a theory description can be accomplished by brute force solving the constraints

//For proving the consistency of axiom sets, assign each derivation with a new number_ n in N. When the independence of each derivation is proved from n, then the axioms satisfy the theory of term-rewriting systems, and hence are valid axiomatic systems
//Inconsistent models can be "salvaged" by a different model that has a dependence on the number_ n. This is horizontal shift, not a vertical shift.
//If a model is inconsistent, it can still produce useful results, by explicitizing the dependence on n, and weakening its theory from "free term-rewriting systems)

using namespace c_star_star::polymorphic;
using namespace c_star_star::number;
using namespace c_star_star::tuples;
using namespace c_star_star::tribool;
using namespace c_star_star::functions;

//A tag class for sequence points
class SequencePoint {
    number_ id;
    friend class  Sequence;
    friend struct std::hash<SequencePoint>;
public:
    bool operator==(const SequencePoint& other) const
    {
        return id == other.id;
    }
    bool operator!=(const SequencePoint& other) const
    {
        return !(*this == other);
    }
};

template<>
struct std::hash<SequencePoint> {
    size_t operator()(const SequencePoint& other) const
    {
        return size_t(other.id % (1ULL << 63));
    }
};

//A set of sequence-points, which are temporally ordered by a single "less than" partial order
//Irreflexive, antisymmetric, transitive
//Add points with a before relation
//Have potentially circular graphs, enforce numerical orderings and locks to assert on circularity
// Locked sequences cannot be further attached to or later unlocked
//TODO: Use tags and domains to enforce numerical locks (ie tag an event A with 4, when adding B after C (and C after A) assert that B's value > 4)
//TODO: Lock a domain permanently, no more inputs into it, and/or no more outputs from it


//Convert a string to a tuple
Tuple parse_tuple(const std::string& is)
{
    TODO;
    Tuple T;
    using boost::spirit::qi::stream;
    using boost::spirit::qi::stream_parser;
    using boost::spirit::qi::parse;
    using boost::spirit::qi::char_;
    using boost::spirit::qi::space;
    using boost::phoenix::push_back;
    using boost::phoenix::ref;
    using boost::phoenix::placeholders::_1;
    //stream_parser<char, number_> num_parser;
    auto num_parser = char_;

    std::vector<number_> temp_num;
    auto parse_action = [&](auto& ctx)->void {
        temp_num.push_back(_attr(ctx));
    };

    //parse(is.begin(), is.end(), char_('[') >> *((+(char_ >> char_(':'))>> char_) % char_(',')) >> char_(']'));



    return T;
}

class Sequence {
public:
    //Start a new sequencepoint, with nothing pointing to it
    SequencePoint newSequencePointStart() {
        FIXME("Add locking, not done yet");
        SequencePoint SP;
        SP.id = ++totalSequencePoints;
        return SP;
    }

    //Associate 2 preexisting sequence points (assert if already has an after)
    void insertNewLink(SequencePoint before, SequencePoint after) {
        ASSUME(not isInBeforeAfter(before), "Should not reassign already assigned SequencePoint!");
        ASSUME(not isInSelectionNodes(before), "Should not reassign already assigned SequencePoint!");
        beforeAfter.insert({ before, after });
    }

    //Create a new sequence point, associate it to "before" and return the new point
    SequencePoint newSequencePointFollower(SequencePoint before) {
        SequencePoint after = newSequencePointStart();
        insertNewLink(before, after);
        return after;
    }

    //Insert a new sequence point with many follows
    SequencePoint newSequencePointChoice(SequencePoint before, IMany sp) {
        SequencePoint after = newSequencePointStart();
        insertNewLink(before, after);
        selectionNodes.insert({ after, sp });
        return after;
    }

    //Follow a single sequence point
    //If no follower, return EmptyAny
    //Otherwise, if simple, return the next point
    //Otherwise, if comnplex, return the zeroth choice
    IAny followSequencePointSimple(SequencePoint before) {
        if (not isInBeforeAfter(before))
            return {};
        else if (isInBeforeAfter(before)) {
            SequencePoint after = beforeAfter.at(before);
            return IAny{ after };
        }
        UNREACHABLE("Cases covered!");
    }

    IAny followSequencePointChoice(SequencePoint before, number_ choice) {
        if (not isInSelectionNodes(before))
            return IAny{};
        IMany choices = selectionNodes[before];
        choices.AssertAllType<SequencePoint>("Must all be SequencePoints");
        if (choices.SizeVector() < to_size_t(choice))
            return IAny{};
        SequencePoint result = choices.nthElementVector(choice).GetCppType<SequencePoint>("Expected SequencePoint");
        return IAny{ result };
    }

    //Follow a choice point, by selecting a choice number_ (0 -> 0th choice, 1 -> 1st choice etc)
    //If the point is not a choice point, only 0 is a valid choice (simple follow)
    //If the index is invalid, return EmptyAny
    IAny followSequencePointAggregate(SequencePoint before, number_ choice) {
        if (choice < 0)
            return IAny{};

        if (not isInBeforeAfter(before) and not isInSelectionNodes(before))
            return IAny{};


        CASES_TRUE(isInBeforeAfter(before), isInSelectionNodes(before));
        if (isInBeforeAfter(before)) {
            if (choice > 0)
                return IAny{};
            return followSequencePointSimple(before);
        }
        else if (isInSelectionNodes(before)) {
            if (selectionNodes[before].SizeVector() < to_size_t(choice))
                return IAny{};

        }
    }

private:
    //A single-key multi-value map from after-points to before-points
    std::unordered_map<SequencePoint, SequencePoint> beforeAfter;
    //A list of nodes with multiple outputs
    std::unordered_map<SequencePoint, IMany> selectionNodes;
    //A number_ associated to each ordering, can be used to enforce far-apart before/after relations
    std::unordered_map<SequencePoint, number_> orderingAssertNumber;
    static number_ totalSequencePoints;

    //If beforeAfter has a "before"
    bool isInBeforeAfter(SequencePoint before) const {
        return not (beforeAfter.contains(before));
    }

    //If selectionNodes has a "before"
    bool isInSelectionNodes(SequencePoint before) const {
        return not (selectionNodes.contains(before));
    }
};

number_ Sequence::totalSequencePoints = 0;

int main() {

}