
#include "Main.h"

#include "Asserts/ConfigReleaseChecked.h"
#include "Datatypes/Number.h"
#include "Utils/GenerationalPointer.cpp"
#include "Utils/IComparison.cpp"
#include "Polymorphic/IAny.cpp"
#include "Polymorphic/IMany.cpp"
#include "Interpreter/IMacroList.cpp"
#include "Datatypes/Tuple.cpp"
#include "Datatypes/Function.cpp"

//TODOs:
//Remove all IManys after prototyping
//Use generationalPointers for regular pointers
//Postconditions/preconditions for everything: test only function-related values, test all class invariants, don't test interfunctional relations with conditions
//Change all numeric integer types to number_ (all indices etc)
//  Find library that's "optimized for small case"
//Convert everything to free functions (Add UFCS later)
//Combine SequenceBuilder and FunctionBuilder; Separate out Function and Sequence execution
//A class to implement the static max_id; map<id, data>; value() = map[id] pattern (Use a single max_id for all classes)

//Design:
/*
*   Describe an imperative, low-level language over Tuples, with determinism, purity, and static_asserts
*       Includes Sequences, Functions, Sequence Executions
*       The "type" of a sequence is the full definition of it, the type of a pure function is the map of its inputs to outputs
*   Describe a "heritable meta-context" describing impure additions to the low-level language and hygienic macros
*   Describe a higher-level language, representing an "optimization contract" over the lower-level language
*       describes the allowed optimizations of the implemented code
*       include theories and static_asserts; describe the allowed/expected behaviours
*/

//Optimizations:

//"Free" optimizations: (Can be performed without non-trivial search optimizations)
//Propagate constants fully
//Replace all variables with (function+state) such that it evaluates equal to the variable at that value
//Monomorphize all function calls on the call-site  f(int a, int b) -> f(3, b) etc
//Monomorphize all theories (eg int a, b; -> int1 a; int2 b;)
//Strengthen all theories from the end  int c := a + b -> int(a + b) c := a + b
// Reduce function-types of outputs' codomain to match function-types of inputs' domain
//Delay all computation "production" until "consumption" in the sequence
//Weaken all theories to only match requirements for all "consumption"

//Purify pass:
//Strength reduction of bounded loops to for(i = 0; i != ...; i++) { /*No writes to i*/; }
//Eliminate all bounded recursion with monomorphization (ie f(3, a) = f(2, b) + c becomes f_3(a) = f_2(b) + c)
//  Transform to non-recursive functions with basecases
//Sequence-Invariant code motion: Useful for loops and branches
//  Moves code representing constraints "outside" sequences that retain those constraints
//Replace all variables with "const shadowing CoWs"
//  ie a = a+1
//   to
//  a2 = a1 + 1
//Merge all unbounded loops program-wide into a single unbounded loop with a single inductor+local variables
//  eg convert 
//      generate(x):
//          co_return next x;
//      generate(y):
//          co_return next y;
//      generate(z):
//          generate(x);
//          generate(y);
//          co_return next z;
//      to
//      generate(z):
//          next x;
//          next y;
//          co_return next z;

//Search pass: (Opposites)
//Monomorphize functions <-> deduplicate ("template-ize") functions
//Inline function calls <-> extract function calls
//Cache vs "functionize" pure variables
//eg
//  a = b + c
//  f(a)
// to/from
//  f(b + c)
//Complete "conditional" theories by solving for the unconditional result, to facilitate "Sequence-invariant code motion"

//Representation pass:
//Represent theories with restrictions on Tuples (ie f[input] = fixed)
//Solve for theory representations by solving (f[input] = fixed)
// Functions with multiple inputs (by tying multiple inputs together)
// Functions that are partially applied are functions with some inputs specified
// 
//Describe "infinities" with generators, switch between different stateless representations
//Purify all computation with "pure" and "impure" sections, separating their cones of influence
// 
// Equivalence class relations split the input into two factors; an equivalence member and an equivalence result
// The "equivalence result" is a single unique representation of the equivalence class
// Different members of the equivalence class can be represented with equivalence results, and can be compared (both == and !=) by comparing the equivalence result
// The equivalence result can be found by brute-forcing the solution to "equivalence_class[a] == equivalence_class[b]"
//
//eg can represent infinity with x such that x - 1 = x (the result of x - 1 has been generated by the definition)
//Representing a generator over a different domain needs (possibly hidden) statefulness, but without representation is stateless
//eg Infinity can also be represented like x such that n < x for all n in N.
//  This can be "approximated statefully" by using a number_ n', which is actually in N, but is bigger than all elements in the discourse.
//  These approximations have to be stateful because eg the "discourse" is stateful (eg as new inputs are received, the "largest" number_ has to be increased)
//  Generating a "stateful" approximation from a theory description can be accomplished by brute force solving the constraints

//For proving the consistency of axiom sets, assign each derivation with a new number_ n in N. When the independence of each derivation is proved from n, then the axioms satisfy the theory of term-rewriting systems, and hence are valid axiomatic systems
//Inconsistent models can be "salvaged" by a different model that has a dependence on the number_ n. This is horizontal shift, not a vertical shift.
//If a model is inconsistent, it can still produce useful results, by explicitizing the dependence on n, and weakening its theory from "free term-rewriting systems)

using namespace c_star_star::polymorphic;
using namespace c_star_star::number;
using namespace c_star_star::tuples;
using namespace c_star_star::tribool;
using namespace c_star_star::functions;

//A tag class for sequence points
class SequencePoint {
    number_ id;
    friend class  Sequence;
    friend struct std::hash<SequencePoint>;
public:
    bool operator==(const SequencePoint& other) const
    {
        return id == other.id;
    }
    bool operator!=(const SequencePoint& other) const
    {
        return !(*this == other);
    }
};
template<>
struct std::hash<SequencePoint> {
    size_t operator()(const SequencePoint& other) const
    {
        return size_t(other.id % (1ULL << 63));
    }
};

//A set of sequence-points, which are temporally ordered by a single "less than" partial order
//Irreflexive, antisymmetric, transitive
//Add points with a before relation
//Have potentially circular graphs, enforce numerical orderings and locks to assert on circularity
// Locked sequences cannot be further attached to or later unlocked
//TODO: Use tags and domains to enforce numerical locks (ie tag an event A with 4, when adding B after C (and C after A) assert that B's value > 4)
//TODO: Lock a domain permanently, no more inputs into it, and/or no more outputs from it
class Sequence {
public:
    //Start a new sequencepoint, with nothing pointing to it
    SequencePoint newSequencePointStart() {
        FIXME("Add locking, not done yet");
        SequencePoint SP;
        SP.id = ++totalSequencePoints;
        return SP;
    }

    //Associate 2 preexisting sequence points (assert if already has an after)
    void insertNewLink(SequencePoint before, SequencePoint after) {
        ASSUME(not isInBeforeAfter(before), "Should not reassign already assigned SequencePoint!");
        ASSUME(not isInSelectionNodes(before), "Should not reassign already assigned SequencePoint!");
        beforeAfter.insert({ before, after });
    }

    //Create a new sequence point, associate it to "before" and return the new point
    SequencePoint newSequencePointFollower(SequencePoint before) {
        SequencePoint after = newSequencePointStart();
        insertNewLink(before, after);
        return after;
    }

    //Insert a new sequence point with many follows
    SequencePoint newSequencePointChoice(SequencePoint before, IMany sp) {
        SequencePoint after = newSequencePointStart();
        insertNewLink(before, after);
        selectionNodes.insert({ after, sp });
        return after;
    }

    //Follow a single sequence point
    //If no follower, return EmptyAny
    //Otherwise, if simple, return the next point
    //Otherwise, if comnplex, return the zeroth choice
    IAny followSequencePointSimple(SequencePoint before) {
        if (not isInBeforeAfter(before))
            return {};
        else if (isInBeforeAfter(before)) {
            SequencePoint after = beforeAfter.at(before);
            return IAny{ after };
        }
        UNREACHABLE("Cases covered!");
    }

    IAny followSequencePointChoice(SequencePoint before, number_ choice) {
        if (not isInSelectionNodes(before))
            return IAny{};
        IMany choices = selectionNodes[before];
        choices.AssertAllType<SequencePoint>("Must all be SequencePoints");
        if (choices.SizeVector() < to_size_t(choice))
            return IAny{};
        SequencePoint result = choices.nthElementVector(choice).GetCppType<SequencePoint>("Expected SequencePoint");
        return IAny{ result };
    }

    //Follow a choice point, by selecting a choice number_ (0 -> 0th choice, 1 -> 1st choice etc)
    //If the point is not a choice point, only 0 is a valid choice (simple follow)
    //If the index is invalid, return EmptyAny
    IAny followSequencePointAggregate(SequencePoint before, number_ choice) {
        if (choice < 0)
            return IAny{};

        if (not isInBeforeAfter(before) and not isInSelectionNodes(before))
            return IAny{};
        
        
        CASES_TRUE(isInBeforeAfter(before), isInSelectionNodes(before));
        if (isInBeforeAfter(before)) {
            if (choice > 0)
                return IAny{};
            return followSequencePointSimple(before);
        }
        else if (isInSelectionNodes(before)) {
            if (selectionNodes[before].SizeVector() < to_size_t(choice))
                return IAny{};

        }
    }

private:
    //A single-key multi-value map from after-points to before-points
    std::unordered_map<SequencePoint, SequencePoint> beforeAfter;
    //A list of nodes with multiple outputs
    std::unordered_map<SequencePoint, IMany> selectionNodes;
    //A number_ associated to each ordering, can be used to enforce far-apart before/after relations
    std::unordered_map<SequencePoint, number_> orderingAssertNumber;
    static number_ totalSequencePoints;

    //If beforeAfter has a "before"
    bool isInBeforeAfter(SequencePoint before) const {
        return not (beforeAfter.contains(before));
    }

    //If selectionNodes has a "before"
    bool isInSelectionNodes(SequencePoint before) const {
        return not (selectionNodes.contains(before));
    }
};

number_ Sequence::totalSequencePoints = 0;


//Builds a Function from C++ code
class FunctionBuilder {
public:
    
    enum class FunctionBuilderNodeTypes {
        Uninitialized,          //Error on usage
        ConstantTerminal,       //Represent a Constant Tuple
        VariableTerminal,       //Represent a Variable
        FunctionPlus,           //Build expression a + b
        FunctionMinus,          //Build expression a - b
        FunctionProduct,        //Build expression a * b
        FunctionQuotient,       //Build expression a / b
        FunctionMod,            //Build expression a % b
        FunctionPointwiseLess,     //Build expression a[i] < b[i] ? c[i] : d[i]
        FunctionPiecewiseLess,     //Build expression i < a[0] ? b[i] : c[i]
        FunctionLexicographicLess, //Build expression a L< b ? c : d
        FunctionGetIndex,          //Build Result[0] = a[b[0]]
        FunctionSetIndex,       //Build Result[a[0]] = b[0]
        FunctionBorrowedNode,   //Build recursive call
        UnsetBorrowFromNode,    //The node that is borrowed from
        SetBorrowFrom,          //A "borrow from" node that is set to another function
        CallFunctionNode,       //Calls a prebuilt function
    };

    number_ builder_id = 0;
    static number_ max_builder_id;
    static std::unordered_map<number_, IMany> data_static;
    static std::unordered_map<number_, FunctionBuilderNodeTypes> node_types;
    static std::unordered_map<number_, std::string> names;

    FunctionBuilderNodeTypes& FunctionBuilderNode() {
        if (not node_types.contains(builder_id)) {
            node_types[builder_id] = FunctionBuilderNodeTypes::Uninitialized;
        }

        return node_types[builder_id];
    }

    const FunctionBuilderNodeTypes& FunctionBuilderNode() const {
        if (not node_types.contains(builder_id)) {
            node_types[builder_id] = FunctionBuilderNodeTypes::Uninitialized;
        }

        return node_types[builder_id];
    }

    IMany& data() {
        return data_static[builder_id];
    }

    const IMany& data() const {
        return data_static[builder_id];
    }

    std::string& name() {
        return names[builder_id];
    }

    const std::string& name() const {
        return names[builder_id];
    }

    static bool isNotUninitialized(const FunctionBuilder S) {
        if (S.FunctionBuilderNode() == FunctionBuilderNodeTypes::Uninitialized)
            return false;
        else if (S.FunctionBuilderNode() != FunctionBuilderNodeTypes::Uninitialized)
            return true;
        UNREACHABLE("True or not true");
        return {};
    }

    FunctionBuilder() {
        builder_id = ++max_builder_id;
        FunctionBuilderNode() = FunctionBuilderNodeTypes::Uninitialized;
        data().clear();
        name() = "";
    }

    FunctionBuilder(Tuple T): FunctionBuilder() {
        FunctionBuilderNode() = FunctionBuilderNodeTypes::ConstantTerminal;
        data().InsertTypeEnd(T);
    }

    FunctionBuilder(number_ n): FunctionBuilder() {
        FunctionBuilderNode() = FunctionBuilderNodeTypes::ConstantTerminal;
        data().InsertTypeEnd(Tuple(n));
    }

    FunctionBuilder(std::integral auto n) : FunctionBuilder() {
        FunctionBuilderNode() = FunctionBuilderNodeTypes::ConstantTerminal;
        data().InsertTypeEnd(Tuple(n));
    }

    FunctionBuilder(Function F) : FunctionBuilder() {
        FunctionBuilderNode() = FunctionBuilderNodeTypes::CallFunctionNode;
        data().InsertTypeEnd(F);
    }

    void setName(std::string s) {
        name() = s;
    }

    static FunctionBuilder Variable(){
        FunctionBuilder SB;
        SB.FunctionBuilderNode() = FunctionBuilderNodeTypes::VariableTerminal;
        SB.data().clear();
        return SB;
    }

    static FunctionBuilder BorrowFrom() {
        FunctionBuilder SB;
        SB.FunctionBuilderNode() = FunctionBuilderNodeTypes::UnsetBorrowFromNode;
        SB.data().clear();
        Function top;
        SB.data().InsertTypeEnd(top);
        return SB;
    }

    FunctionBuilder operator+(const FunctionBuilder rhs) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(rhs), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(rhs);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionPlus;
        ASSUME(result.data().SizeVector() == 2, "Must have 2 elements!");
        result.data().AssertAllType<FunctionBuilder>("Must have 2 FunctionBuilders!");
        return result;
    }

    FunctionBuilder operator-(const FunctionBuilder rhs) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(rhs), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(rhs);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionMinus;
        return result;
    }

    FunctionBuilder operator*(const FunctionBuilder rhs) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(rhs), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(rhs);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionProduct;
        return result;
    }

    FunctionBuilder operator/(const FunctionBuilder rhs) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(rhs), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(rhs);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionQuotient;
        return result;
    }

    FunctionBuilder operator%(const FunctionBuilder rhs) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(rhs), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(rhs);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionMod;
        return result;
    }

    FunctionBuilder operator[](const FunctionBuilder index) const {
        return GetIndex(index);
    }

    FunctionBuilder operator-() const {
        const FunctionBuilder& lhs = *this;
        const FunctionBuilder& rhs = Tuple(-1);
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(rhs);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionProduct;
        return result;
    }

    class PolyTuple {
        Tuple T;
    public:
        PolyTuple(Tuple T) : T(T) {}

        PolyTuple(number_ n): T(n) {}
        template<std::integral Int>
        PolyTuple(Int n) : T(number_(n)){}
        operator Tuple() const { return T; }

        PolyTuple(std::initializer_list<number_> l) {
            auto l_iterator = l.begin();
            for (int i = 0; l_iterator != l.end(); i++, l_iterator++) {
                T.data[i] = *l_iterator;
            }
        }
    };

    FunctionBuilder(PolyTuple i) : FunctionBuilder() {
        FunctionBuilderNode() = FunctionBuilderNodeTypes::ConstantTerminal;
        data().InsertTypeEnd(Tuple(i));
    }

    //Build Expression FunctionBorrowedNode
    FunctionBuilder operator()(const FunctionBuilder shrink, const PolyTuple basecase) const {
        ASSUME(isNotUninitialized(shrink), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(*this);
        result.data().InsertTypeEnd<FunctionBuilder>(shrink);
        result.data().InsertTypeEnd<Tuple>(basecase);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionBorrowedNode;
        return result;
    }

    //Apply the function to the output of F rather than input
    FunctionBuilder operator()(const FunctionBuilder F) const {
        const FunctionBuilder& applier = *this;
        ASSUME(isNotUninitialized(applier), "Must be initialized!");
        ASSUME(isNotUninitialized(F), "Must be initialized!");
        return ReplaceIdentity(F);
    }

    friend IComparisonToBool operator==(const FunctionBuilder& a, const FunctionBuilder& b) {
        if (a.builder_id != b.builder_id)
            return false;
        else if (a.builder_id == b.builder_id)
            return true;
        UNREACHABLE("operator==");
    }

    void operator^=(const FunctionBuilder& F) {
        setBorrowed(F);
    }

    //Returns a function that can evaluate the constructed builder
    Function buildFunction() const {
        Function return_value;
        switch (FunctionBuilderNode())
        {
        case FunctionBuilder::FunctionBuilderNodeTypes::Uninitialized: {
            PANIC("Uninitialized!");
            return {};
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::ConstantTerminal: {
            ASSERT(data().SizeVector() == 1, "Expecting 1 element!");
            Tuple ConstantValue = data().pickLast().GetCppType<Tuple>();
            return_value.SetConstant(ConstantValue);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::VariableTerminal: {
            ASSERT(data().SizeVector() == 0, "Expecting no element!");
            return_value.SetIdentity();
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionPlus: {
            ASSERT(data().SizeVector() == 2, "Expecting 2 elements!");
            data().AssertAllType<FunctionBuilder>("Expecting 2 FunctionBuilders!");
            IAny a1 = data().nthElementVector(0);
            FunctionBuilder FB1 = a1.GetCppType<FunctionBuilder>();
            Function F1 = FB1.buildFunction();
            Function F2 = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetAddFunction(F1, F2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionMinus: {
            ASSERT(data().SizeVector() == 2, "Expecting 2 elements!");
            Function F1 = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function F2 = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetSubtractFunction(F1, F2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionProduct: {
            ASSERT(data().SizeVector() == 2, "Expecting 2 elements!");
            Function F1 = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function F2 = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetProductFunction(F1, F2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionQuotient: {
            ASSERT(data().SizeVector() == 2, "Expecting 2 elements!");
            Function F1 = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function F2 = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetQuotientFunction(F1, F2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionMod: {
            ASSERT(data().SizeVector() == 2, "Expecting 2 elements!");
            Function F1 = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function F2 = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetRemainderFunction(F1, F2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionPointwiseLess: {
            ASSERT(data().SizeVector() == 4, "Expecting 4 elements!");
            Function value = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function test = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            Function alt_1 = data().nthElementVector(2).GetCppType<FunctionBuilder>().buildFunction();
            Function alt_2 = data().nthElementVector(3).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetPointwiseLess(value, test, alt_1, alt_2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionPiecewiseLess: {
            ASSERT(data().SizeVector() == 3, "Expecting 3 elements!");
            Function alt_1 = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function threshold = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            Function alt_2 = data().nthElementVector(2).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetPiecewiseLess(threshold, alt_1, alt_2);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionLexicographicLess: {
            ASSERT(data().SizeVector() == 4, "Expecting 4 elements!");
            Function F0 = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function F1 = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            Function F2 = data().nthElementVector(2).GetCppType<FunctionBuilder>().buildFunction();
            Function F3 = data().nthElementVector(3).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetLexicographicLess(F0, F1, F2, F3);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionGetIndex: {
            ASSERT(data().SizeVector() == 2, "Expecting 2 elements!");
            Function tuple = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function index = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetGetIndex(index, tuple);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionSetIndex: {
            ASSERT(data().SizeVector() == 2, ((std::string)"Expecting 2 elements! Found: " + std::to_string(data().SizeVector())).c_str());
            Function tuple = data().nthElementVector(0).GetCppType<FunctionBuilder>().buildFunction();
            Function index = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            return_value.SetSetIndex(index, tuple);
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::FunctionBorrowedNode: {
            //Construct the BorrowNode
            ASSERT(data().SizeVector() == 3, "Expecting 3 elements!");
            //Get the stored function object:
            //Get the reference to the recursive call
            FunctionBuilder top_builder = (data().nthElementVector(0).GetCppType<FunctionBuilder>());
            ASSERT(top_builder.FunctionBuilderNode() == FunctionBuilderNodeTypes::SetBorrowFrom, "Must be set before construction");
            //Retrieve the stored function object from the recursive call object
            Function top = top_builder.data().nthElementVector(0).GetCppType<Function>();
            Function shrink = data().nthElementVector(1).GetCppType<FunctionBuilder>().buildFunction();
            Tuple    basecase = data().nthElementVector(2).GetCppType<Tuple>();
            return_value.SetBorrow(shrink, basecase, top);
            
            //The "set" value, containing the final recursive call
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::UnsetBorrowFromNode: {
            PANIC("Construction of an unset borrow-from node. Must set it first");
            UNREACHABLE("Panic");
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::SetBorrowFrom: {
            //The returned function_id must match the function_id of the stored function
            //Get the target functionbuilder
            FunctionBuilder target = data().nthElementVector(1).GetCppType<FunctionBuilder>();
            //This will call the "build" on the recursive operation
            //This call will call the switch at FunctionBuilder::FunctionBuilderNodeTypes::FunctionBorrowedNode
            // which will receive the zeroth element of this data, which is the function constructed here

            //id of return_value is this
            return_value = data().nthElementVector(0).GetCppType<Function>();
            
            //values associated with return_value is this
            //return_value.copyFunction(target.buildFunction());
            Function target_data = target.buildFunction();

            return_value.NodeClass() = target_data.NodeClass();
            return_value.FunctionNodes() = target_data.FunctionNodes();
            break;
        }
        case FunctionBuilder::FunctionBuilderNodeTypes::CallFunctionNode: {
            ASSERT(data().SizeVector() == 1, "Expecting 1 elements!");
            Function F0 = data().nthElementVector(0).GetCppType<Function>();
            return F0;
        }
        default:
            break;
        }
        if (name() != "")
            return_value.name() = name();
        return return_value;
        UNREACHABLE("Unreachable code!");
    }

    std::string print_dbg() {
        TODO_("Improve function builder");
        std::stringstream s;
        s << "Type: " << (int)FunctionBuilderNode() << " ";
        if (FunctionBuilderNode() == FunctionBuilderNodeTypes::VariableTerminal) {
            s << "x";
            return s.str();
        }
        else if (FunctionBuilderNode() == FunctionBuilderNodeTypes::ConstantTerminal) {
            s << "build: [" + data().pickLast().GetCppType<Tuple>().to_str() + "]";
            return s.str();
        }
        else if (FunctionBuilderNode() == FunctionBuilderNodeTypes::UnsetBorrowFromNode) {
            s << "recurse: [" "]";
            return s.str();
        }
        else if (FunctionBuilderNode() == FunctionBuilderNodeTypes::FunctionBorrowedNode) {
            s << "recurse: [" "]";
            return s.str();
        }
        else {
            s << "Elements: [";
            IMany::MonoVoidFunction PrintRecursive = [&s](IAny element) -> void {
                if (+element.HasCPPType<FunctionBuilder>()) {
                    s << element.GetCppType<FunctionBuilder>("").print_dbg() << ", ";
                    return;
                }
                else
                    return;
            };
            data().OperateElement(PrintRecursive);
            s << "]";
            return s.str();
        }
    }

private:
    FunctionBuilder ReplaceIdentity(const FunctionBuilder& F) const {
        if (FunctionBuilderNode() == FunctionBuilderNodeTypes::VariableTerminal) {
            return F;
        }
        else if (FunctionBuilderNode() == FunctionBuilderNodeTypes::ConstantTerminal) {
            return *this;
        }
        else {
            IMany::MonoAnyFunction ReplaceRecursive = [&](IAny element) -> IAny { 
                if (+element.HasCPPType<FunctionBuilder>())
                    return IAny{ element.GetCppType<FunctionBuilder>("").ReplaceIdentity(F) };
                else
                    return element;
            };
            FunctionBuilder FB = *this;
            FB.data() = data().TransformMap(ReplaceRecursive);
            //Everything else is unchanged, only data() is recursively transformed
            return FB;
        }
        UNREACHABLE("If-else");
    }

    //Sets a borrowed-from node to its value
    void setBorrowed(const FunctionBuilder& F) {
        number_ x = builder_id;
        ASSUME(FunctionBuilderNode() == FunctionBuilderNodeTypes::UnsetBorrowFromNode, "Can only set Borrowed-from nodes!");
        ASSUME(F.FunctionBuilderNode() != FunctionBuilderNodeTypes::UnsetBorrowFromNode, "Cannot set to Borrowed-from nodes!");
        //When building it, return this function
        //When building recursive calls to this, use this function for "top"
        data().clear();
        data().InsertTypeEnd<Function>(Function());
        data().InsertTypeEnd(F);
        FunctionBuilderNode() = FunctionBuilderNodeTypes::SetBorrowFrom;
        ASSUME(FunctionBuilderNode() == FunctionBuilderNodeTypes::SetBorrowFrom, "It remains a recursive call!");
        ASSUME(builder_id == x, "builder_id should not change!");
    }

    struct SetTypeOP;
    friend class LexicographicCase2;
    friend class PointwiseCase2;
    friend class PiecewiseCase1;
    friend struct SetType;
    friend FunctionBuilder operator||(LexicographicCase2 PC, FunctionBuilder alt_2);
    friend FunctionBuilder operator||(PointwiseCase2 PC, FunctionBuilder alt_2);
    friend FunctionBuilder operator|(PiecewiseCase1 PC, FunctionBuilder alt_2);

    //Build expression a[i] < b[i] ? c[i] : d[i]
    static FunctionBuilder BuildPointwiseLess(const FunctionBuilder value, const FunctionBuilder test, const FunctionBuilder alt1, const FunctionBuilder alt2) {
        ASSUME(isNotUninitialized(value), "Must be initialized");
        ASSUME(isNotUninitialized(test), "Must be initialized");
        ASSUME(isNotUninitialized(alt1), "Must be initialized");
        ASSUME(isNotUninitialized(alt2), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(value);
        result.data().InsertTypeEnd<FunctionBuilder>(test);
        result.data().InsertTypeEnd<FunctionBuilder>(alt1);
        result.data().InsertTypeEnd<FunctionBuilder>(alt2);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionPointwiseLess;
        return result;
    }

    //Build expression i < index ? alt_1[i] : alt_2[i]
    static FunctionBuilder BuildPiecewiseLess(const FunctionBuilder alt_1, const FunctionBuilder index, const FunctionBuilder alt_2) {
        ASSUME(isNotUninitialized(alt_1), "Must be initialized");
        ASSUME(isNotUninitialized(index), "Must be initialized");
        ASSUME(isNotUninitialized(alt_2), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(alt_1);
        result.data().InsertTypeEnd<FunctionBuilder>(index);
        result.data().InsertTypeEnd<FunctionBuilder>(alt_2);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionPiecewiseLess;
        return result;
    }

    //Build expression a < b ? c : d
    static FunctionBuilder BuildLexicographicLess(const FunctionBuilder value, const FunctionBuilder test, const FunctionBuilder alt_1, const FunctionBuilder alt_2) {
        ASSUME(isNotUninitialized(value), "Must be initialized");
        ASSUME(isNotUninitialized(test), "Must be initialized");
        ASSUME(isNotUninitialized(alt_1), "Must be initialized");
        ASSUME(isNotUninitialized(alt_2), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(value);
        result.data().InsertTypeEnd<FunctionBuilder>(test);
        result.data().InsertTypeEnd<FunctionBuilder>(alt_1);
        result.data().InsertTypeEnd<FunctionBuilder>(alt_2);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionLexicographicLess;
        return result;
    }

    //Build Expression result[0] = lhs[index[0]]
    FunctionBuilder GetIndex(const FunctionBuilder index) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(index), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(index);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionGetIndex;
        return result;
    }

    //Build Expression result[index[0]] = lhs[0]
    FunctionBuilder SetIndex(const FunctionBuilder index) const {
        const FunctionBuilder& lhs = *this;
        ASSUME(isNotUninitialized(lhs), "Must be initialized");
        ASSUME(isNotUninitialized(index), "Must be initialized");
        FunctionBuilder result;
        result.data().InsertTypeEnd<FunctionBuilder>(lhs);
        result.data().InsertTypeEnd<FunctionBuilder>(index);
        result.FunctionBuilderNode() = FunctionBuilderNodeTypes::FunctionSetIndex;
        return result;
    }

public:
    FunctionBuilder operator[](SetTypeOP S) const;
};

std::unordered_map<number_, IMany> FunctionBuilder::data_static{};
number_ FunctionBuilder::max_builder_id = 0;
std::unordered_map<number_, FunctionBuilder::FunctionBuilderNodeTypes> FunctionBuilder::node_types;
std::unordered_map<number_, std::string> FunctionBuilder::names;

FunctionBuilder const_(FunctionBuilder::PolyTuple i) {
    return i;
}

const FunctionBuilder var_ = FunctionBuilder::Variable();

class PointwiseCase1;
class PointwiseCase2;

class PointwiseCase1 {
public:
    FunctionBuilder test;
    FunctionBuilder value;

    PointwiseCase1(FunctionBuilder value, FunctionBuilder test);
    friend PointwiseCase2 operator||(PointwiseCase1 PC, FunctionBuilder alt_1);
};

class PointwiseCase2 {
    FunctionBuilder test;
    FunctionBuilder value;
    FunctionBuilder alt_1;
public:
    PointwiseCase2(FunctionBuilder value, FunctionBuilder test, FunctionBuilder alt_1);
    friend FunctionBuilder operator||(PointwiseCase2 PC, FunctionBuilder alt_2);
};

PointwiseCase1::PointwiseCase1(FunctionBuilder value, FunctionBuilder test) : value(value), test(test) {}
PointwiseCase2::PointwiseCase2(FunctionBuilder value, FunctionBuilder test, FunctionBuilder alt_1) : test(test), value(value), alt_1(alt_1) {}

PointwiseCase2 operator||(PointwiseCase1 PC, FunctionBuilder alt_1) { return PointwiseCase2(PC.value, PC.test, alt_1); }
FunctionBuilder operator||(PointwiseCase2 PC, FunctionBuilder alt_2) { return FunctionBuilder::BuildPointwiseLess(PC.value, PC.test, PC.alt_1, alt_2); }
PointwiseCase1 operator<(FunctionBuilder value, FunctionBuilder test) { return PointwiseCase1(value, test); }
PointwiseCase1 operator>(FunctionBuilder value, FunctionBuilder test) { return PointwiseCase1(test, value); }




//alt_1 | test | alt_2
class PiecewiseCase1;

class PiecewiseCase1 {
public:
    FunctionBuilder index;
    FunctionBuilder alt_1;

    PiecewiseCase1(FunctionBuilder value, FunctionBuilder test);
    friend FunctionBuilder operator|(PiecewiseCase1 PC, FunctionBuilder alt_1);
};

PiecewiseCase1::PiecewiseCase1(FunctionBuilder alt_1, FunctionBuilder index) : alt_1(alt_1), index(index) {}

FunctionBuilder operator|(PiecewiseCase1 PC, FunctionBuilder alt_2) { return FunctionBuilder::BuildPiecewiseLess(PC.alt_1, PC.index, alt_2); }
PiecewiseCase1 operator|(FunctionBuilder alt_1, FunctionBuilder index) { return PiecewiseCase1(alt_1, index); }


class LexicographicCase1;
class LexicographicCase2;

class LexicographicCase1 {
public:
    FunctionBuilder test;
    FunctionBuilder value;

    LexicographicCase1(FunctionBuilder value, FunctionBuilder test);
    friend LexicographicCase2 operator||(LexicographicCase1 PC, FunctionBuilder alt_1);
};

class LexicographicCase2 {
    FunctionBuilder test;
    FunctionBuilder value;
    FunctionBuilder alt_1;
public:
    LexicographicCase2(FunctionBuilder value, FunctionBuilder test, FunctionBuilder alt_1);
    friend FunctionBuilder operator||(LexicographicCase2 PC, FunctionBuilder alt_2);
};

LexicographicCase1::LexicographicCase1(const FunctionBuilder value, const FunctionBuilder test) : value(value), test(test) {}
LexicographicCase2::LexicographicCase2(const FunctionBuilder value, const FunctionBuilder test, const FunctionBuilder alt_1) : test(test), value(value), alt_1(alt_1) {}

LexicographicCase2 operator||(const LexicographicCase1 PC, const FunctionBuilder alt_1) { return LexicographicCase2(PC.value, PC.test, alt_1); }
FunctionBuilder operator||(const LexicographicCase2 PC, const FunctionBuilder alt_2) { return FunctionBuilder::BuildLexicographicLess(PC.value, PC.test, PC.alt_1, alt_2); }
LexicographicCase1 operator<<(const FunctionBuilder value, const FunctionBuilder test) { return LexicographicCase1(value, test); }
LexicographicCase1 operator>>(const FunctionBuilder value, const FunctionBuilder test) { return LexicographicCase1(test, value); }

struct FunctionBuilder::SetTypeOP {
    FunctionBuilder F;
    SetTypeOP(FunctionBuilder F) : F(F) {}
};

struct SetType {
    FunctionBuilder::SetTypeOP operator>>(const FunctionBuilder F) const {
        return FunctionBuilder::SetTypeOP(F);
    }
} set;

FunctionBuilder FunctionBuilder::operator[](const SetTypeOP S) const {
    return FunctionBuilder::SetIndex(S.F);
}

//If Test(x) == case_, return Value(x), else return Main(x);
static FunctionBuilder CreateCase(Tuple case_, FunctionBuilder Value, FunctionBuilder Main, FunctionBuilder Test) {
    FunctionBuilder Identity = var_;
    FunctionBuilder Case = case_;
    FunctionBuilder IsLess = Test << Case || Main || Value;
    FunctionBuilder IsMore = Case << Test || Main || IsLess;
    return IsMore;
}

//base[index] = value, base[!index] = base
static FunctionBuilder CreatePiecewiseAt(FunctionBuilder base, FunctionBuilder index, FunctionBuilder value) {
    //F[-Inf:Index -1] = base; F[Index:Index] = value; F[Index +1:Inf] = base;
    FunctionBuilder FinalResult = base | index | value | index + 1 | base;
    return FinalResult;
}

//Return a function that performs pointwise x < 0 ? -x : x
static FunctionBuilder PointwiseAbs(FunctionBuilder base) {
    FunctionBuilder abs = var_ < 0 || -base || base;
    return abs;
}

//A tuple variable that always evaluates f[input_] = value
//Can be used to represent types
class ConstrainedTuple {
    Function Process;
    Tuple Target;
public:
    ConstrainedTuple(Function Process, Tuple Target) : Process(Process), Target(Target) {}
    void AssertTuple(Tuple T) {
        Tuple test = Process(T);
        IComparisonResult x = Tuple::isEqual(test, Target);
        if (+x) {
            return;
        }
        else if (!x) {
            std::string message = "";
            message += "Assertion failure!";
            message += "\nThe tested Tuple is: ";
            message += T.to_str();
            message += "\nThe function evaluation is: ";
            message += test.to_str();
            message += "\nThe target is: ";
            message += Target.to_str();
            PANIC(message.c_str());
            return;
        }
        else {
            UNREACHABLE("Is known");
        }
    }
};

//Mini-class to aid inline construction
class ConstrainedTupleTarget {
    friend class ConstrainedTuple;
public:
    Tuple target;
    ConstrainedTupleTarget(FunctionBuilder::PolyTuple input) : target(input) {}
};

ConstrainedTuple operator&=(FunctionBuilder fB, ConstrainedTupleTarget ctt) {
    return ConstrainedTuple{ fB.buildFunction(), ctt.target };
}

ConstrainedTupleTarget ctt_(FunctionBuilder::PolyTuple input) { return ConstrainedTupleTarget(input); }

//Convert a string to a tuple
Tuple parse_tuple(const std::string& is)
{
    TODO;
    Tuple T;
    using boost::spirit::qi::stream;
    using boost::spirit::qi::stream_parser;
    using boost::spirit::qi::parse;
    using boost::spirit::qi::char_;
    using boost::spirit::qi::space;
    using boost::phoenix::push_back;
    using boost::phoenix::ref;
    using boost::phoenix::placeholders::_1;
    //stream_parser<char, number_> num_parser;
    auto num_parser = char_;

    std::vector<number_> temp_num;
    auto parse_action = [&](auto& ctx)->void {
        temp_num.push_back(_attr(ctx));
    };

    //parse(is.begin(), is.end(), char_('[') >> *((+(char_ >> char_(':'))>> char_) % char_(',')) >> char_(']'));



    return T;
}

class SequencedCall;

//Tie multiple tuples into 1
class SequenceTie {
    IMany Tuples;
public:
    //Retrieve the tied tuple for evaluation
    Tuple ExecuteTie() {
        //Convert a, b, c, into:
        //-3: a[-1], -2: b[-1], -1: c[-1], 0: a[0], 1: b[0], 2: c[0], 3: a[1], ...
        //Map index i of Tuple j to j + (i * n)
        Tuples.AssertAllType<Tuple>("Must store tuples!");
        const number_ n = Tuples.SizeVector();
        if (n == 0) {
            return Tuple{};
        }
        auto map_target_index = [n](number_ in_index, number_ in_tuple)->number_ { return (in_index * n) + in_tuple; };
        auto map_get_index = [n](number_ out_index)->std::pair<number_, number_> { return { out_index / n, out_index % n }; };
        number_ maxHeight = 0;
        number_ minHeight = 0;
        for (const IAny& Tx : Tuples.VectorIterate()) {
            const Tuple& T = Tx.GetCppType<Tuple>("Must only store Tuples!");
            using namespace std;
            maxHeight = max(maxHeight, Tuple::getMaxHeight(T).GetNumberConst_Index(0));
            minHeight = min(minHeight, Tuple::getMinHeight(T).GetNumberConst_Index(0));
        }
        Tuple ret;
        for (number_ i = (minHeight - 1) * n; i <= maxHeight * n; i++) {
            number_ a = 0, b = 0;
            auto z = map_get_index(i);
            a = z.first; b = z.second;
            ASSERT(map_target_index(a, b) == i, "Must be reversible functions");
            Tuple get = Tuples.nthElementVector(b).GetCppType<Tuple>("Must store Tuples!");
            ret.GetNumber_Index(i) = get.GetNumber_Index(a);
        }
        return ret;
    }
    //A function for retrieving the nth Tuple when max are stored
    static FunctionBuilder FunctionBuilderUntie(number_ n, number_ max) { 
        TODO;
    }
    SequenceTie(std::initializer_list<Tuple> l) : Tuples(PolyMany(l)) {}  //Construct a collection of variables
};

//a + b = (Untie(0) + Untie(1))(SequenceTie(a, b))

//Represent variables, tuples, streams etc
//Allocate within the "function tuple"
//Each terminal is a name for a piece of a Tuple; dehardcode the allocator
//Have explicit "tie" and "get" functions for Tuples -> Tuple and Tuple -> Tuples
class SequencedTerminal {
public:
    auto operator=(SequencedTerminal) = delete;
    static number_ max_id;
    number_ id;

    SequencedTerminal() { id = ++max_id; }
    friend bool operator==(const SequencedTerminal& lhs, const SequencedTerminal& rhs) { return lhs.id == rhs.id; }
};
number_ SequencedTerminal::max_id = 0;

//A sequence with associated code
//Has simple sentences (SequenceTerminal = Function(SequenceTerminal))
//If-else statements (if F[a] == b) {} else {};
//Strong loops (for(i = 0; i != n; i++) {no writes to i};)
//Weak loops (while(...) {}) (Maybe runs forever)
class SequencedExecution {
public:
    Sequence Flow;
    enum class SequencedExecutionTypes: int {
        Uninitialized,  //Unitialized variable (not to be used)
        SimpleAssign,   //Terminal = Function(terminals) (void)
        Stream,         //Read from a stream into a terminal
        Chain,          //A list of SequencedExecutions (void)
        If,             //A forward branch (has a mandatory else) (void)
        While,          //A while loop, arbitrary strength (void)
        For,            //A strong for loop (i = 0 to n, i++) { no writes to i; } (void)
    } ExecutionType;
    IMany data;
    static number_ max_id;
    number_ id;

public:
    SequencedExecution() { id = ++max_id; ExecutionType = SequencedExecutionTypes::Uninitialized; }
    SequencedExecution(std::initializer_list<SequencedExecution>) : SequencedExecution() {};
    SequencedCall operator()(std::initializer_list<SequencedTerminal>);
    //Identity
    friend bool operator==(const SequencedExecution& lhs, const SequencedExecution& rhs) { return lhs.id == rhs.id; }
};
number_ SequencedExecution::max_id = 0;

//Represent an expression, involving (possibly) multiple SequencedTerminals
class SequencedFunctionCall {
    IMany vars;                     //Store a list of SequencedFunctionCalls
    FunctionBuilder var_Function;   //The function over the tied together variables

public:
    SequencedFunctionCall() {}
    //Build a functioncall of two functioncalls
    SequencedFunctionCall(SequencedTerminal st) : vars(PolyMany({ st })) { var_Function = var_; }
    friend SequencedFunctionCall operator+(SequencedFunctionCall lhs, SequencedFunctionCall rhs) {
        SequencedFunctionCall SFC;
        SFC.vars.clear();
        SFC.vars.InsertTypeEnd(lhs);
        SFC.vars.InsertTypeEnd(rhs);
        SFC.var_Function = SequenceTie::FunctionBuilderUntie(0, 2) + SequenceTie::FunctionBuilderUntie(1, 2);
        //TODO_("Fix");
        return SFC;
    }
    friend SequencedFunctionCall operator+(SequencedFunctionCall lhs, SequencedTerminal rhs) { return operator+(lhs, SequencedFunctionCall(rhs)); }
    friend SequencedFunctionCall operator+(SequencedTerminal lhs, SequencedFunctionCall rhs) { return operator+(SequencedFunctionCall(lhs), rhs); }
    friend bool operator==(const SequencedFunctionCall& lhs, const SequencedFunctionCall& rhs) { return +IMany::CompareVector(lhs.vars, rhs.vars) and +(lhs.var_Function == rhs.var_Function); }
};

SequencedFunctionCall operator+(SequencedTerminal lhs, SequencedTerminal rhs) { return operator+(SequencedFunctionCall(lhs), SequencedFunctionCall(rhs)); }

//An execution-context defined manner of collapsing into a single value
//eg console input, network management etc
//Use sequences to lock its value as an optimization barrier
//Also use state-machine-esque types to lock the sequence
class SequencedStream {
    enum class StreamKinds {
        uninitialized,
        std_cin,
        std_cout,
    } StreamType = StreamKinds::uninitialized;
public:
    SequencedStream(PolyAny t) {
        if (t == &std::cin) {
            StreamType = StreamKinds::std_cin;
            return;
        }
        else if (t == &std::cout) {
            StreamType = StreamKinds::std_cout;
            return;
        }
        PANIC("Incorrect stream constructor");
    }
    SequencedStream(const SequencedStream&) = default;

    //Read the next tuple from cin
    Tuple ReadNextTuple() {
        CASES(StreamType,
            StreamKinds::std_cin, 
            StreamKinds::std_cout);
        if (StreamType == StreamKinds::std_cin) {
            std::string z;
            return parse_tuple(z);
        }
        else if (StreamType == StreamKinds::std_cout) {
            PANIC("Read from stdout");
            return Tuple{};
        }
        PANIC("UnknownStreamType!");
    }
    void WriteNextTuple(Tuple T) {
        CASES(StreamType,
            StreamKinds::std_cin,
            StreamKinds::std_cout);
        if (StreamType == StreamKinds::std_cin) {
            PANIC("Write to stdin");
            return;
        }
        else if (StreamType == StreamKinds::std_cout) {
            std::cout << T.to_str();
            return;
        }
        PANIC("UnknownStreamType!");
    }
    friend bool operator==(SequencedStream a, SequencedStream b) { return a.StreamType == b.StreamType; }
};

//Set a mutable variable, inside a Sequence
//LHS accepts only terminals
//RHS accepts expressions ie function calls
SequencedExecution operator<=(SequencedTerminal& lhs, SequencedFunctionCall rhs) {
    SequencedExecution ret;
    ret.ExecutionType = SequencedExecution::SequencedExecutionTypes::SimpleAssign;
    ret.data.clear();
    ret.data.InsertTypeEnd(lhs);
    ret.data.InsertTypeEnd(rhs);
    return ret;
}

//Represent the result of a SequenceExecution() - used as part of the definition
class SequencedCall {
    IMany terminal;
public:
    SequencedExecution operator()(std::initializer_list<SequencedExecution> l);
    SequencedCall(std::initializer_list<SequencedTerminal> l): terminal(PolyMany(l)) {}
};
//The function definition object resulting from a call f({parameters})
//Use by attaching ({definition...}) to it
SequencedCall SequencedExecution::operator()(std::initializer_list<SequencedTerminal> l) { return SequencedCall(l); }
//The function code resulting from f({parameters})({definition})
SequencedExecution SequencedCall::operator()(std::initializer_list<SequencedExecution> l) {
    SequencedExecution ret;
    ret.ExecutionType = SequencedExecution::SequencedExecutionTypes::Chain;
    ret.data.clear();
    for (const SequencedExecution& x : l) {
        ret.data.InsertTypeEnd(x);
    }
    return ret;
}

//Assign a constant to a terminal
SequencedExecution operator<=(SequencedTerminal Terminal, FunctionBuilder::PolyTuple Tuple_) {
    SequencedExecution SE;
    SE.ExecutionType = SequencedExecution::SequencedExecutionTypes::SimpleAssign;
    SE.data.clear();
    SE.data.InsertTypeEnd(Terminal);
    SE.data.InsertTypeEnd<Tuple>(Tuple_);
    return SE;
}

//Read from a stream to a terminal
SequencedExecution operator<<(SequencedTerminal ST, SequencedStream SS) {
    SequencedExecution SE;
    SE.data.clear();
    SE.ExecutionType = SequencedExecution::SequencedExecutionTypes::Stream;
    SE.data.InsertTypeEnd(ST);
    SE.data.InsertTypeEnd(SS);
    return SE;
}

//Used for return_ <= ...
class ReturnType{} return_;
//Set the return terminal
SequencedExecution operator<=(ReturnType, SequencedTerminal) { TODO; };

//Use operator() to get the condition: Function(Tuple) = Value
//Use another operator() to get the first alternative: if(cond) then alt_1
//Use another operator() to get the second alternative: if(cond) then alt_1 else alt_2
class SequenceIfAlt2 {
    Function F;
    SequencedTerminal input;
    Tuple target;
    SequencedExecution if_1;
public:
    SequencedExecution operator()(SequencedExecution if_2) {}
    SequenceIfAlt2(Function F, SequencedTerminal input, Tuple target, SequencedExecution if_1) :
        F(F), input(input), target(target), if_1(if_1) {}
};

class SequenceIfAlt1 {
    Function F;
    SequencedTerminal input;
    Tuple target;
public:
    SequenceIfAlt2 operator()(SequencedExecution if_1) { return SequenceIfAlt2(F, input, target, if_1); }
    SequenceIfAlt1(Function F, SequencedTerminal input, Tuple target): F(F), input(input), target(target) {}
};

SequenceIfAlt1 if_(Function F, SequencedTerminal input, Tuple target) { return SequenceIfAlt1(F, input, target); }

class SequenceWhile {
    Function F; SequencedTerminal input; Tuple target;
public:
    SequencedExecution operator()(SequencedExecution loop) { TODO; }
    SequenceWhile(Function F, SequencedTerminal input, Tuple target): F(F), input(input), target(target) {}
};

SequenceWhile while_(Function F, SequencedTerminal input, Tuple target) { return SequenceWhile(F, input, target); }


class SequenceFor {
    SequencedTerminal input, target;
public:
    SequencedExecution operator()(SequencedExecution loop) { TODO; }
    SequenceFor(SequencedTerminal input, SequencedTerminal target) : input(input), target(target) {}
};

SequenceFor for_(SequencedTerminal input, SequencedTerminal target) { return SequenceFor(input, target); }

int main() {

}

#undef ASSERT
#undef ASSUME
#undef UNREACHABLE